#!/bin/bash

# === 🎒 wutuready: One click python project init ===

# 1. 项目名称参数
PROJECT_NAME=$1

if [ -z "$PROJECT_NAME" ]; then
  echo "Please name your project： bash wutuready.sh my-nlp-toolkit"
  exit 1
fi

# 2. 创建项目目录结构
mkdir -p $PROJECT_NAME/{toolbox,tests,.vscode}

cd $PROJECT_NAME

# 3. 初始化 README
cat << EOF > README.md
# $PROJECT_NAME

👋 Welcome to  **$PROJECT_NAME**！
This is a python project stucture generated by wutuready 🐱

EOF

# 4. 初始化 .gitignore
cat << EOF > .gitignore
.venv/
__pycache__/
*.pyc
.DS_Store
.ipynb_checkpoints/
EOF

# 5. 创建 hello.py
cat << EOF > hello.py
def hello(name):
    print(f"Hello, {name}!")

hello("Ready to go! Start coding here:")
EOF

# 6. toolbox/__init__.py
touch toolbox/__init__.py
cat << EOF > toolbox/model_check.py

EOF

# 7. 初始化虚拟环境并激活
python3 -m venv .venv
source .venv/bin/activate

# 8. 安装 black 并 freeze 依赖
pip install black
pip freeze > requirements.txt

# 9. 写 VS Code 设置
cat << EOF > .vscode/settings.json
{
  "editor.formatOnSave": true,
  "editor.formatOnSaveMode": "file",
  "python.formatting.provider": "black",
  "python.defaultInterpreterPath": "\${workspaceFolder}/.venv/bin/python",
  "[python]": {
    "editor.defaultFormatter": "ms-python.black-formatter"
  }
}
EOF

# 10. 初始化 Git 仓库
git init
git add .
git commit -m "🎉 wutuready: $PROJECT_NAME has been created"

# ✅ 完成提示
echo "✅ '$PROJECT_NAME' is now ready to go!"
echo "💻 Start from the following commands:"
echo ""
echo "    cd $PROJECT_NAME"
echo "    source .venv/bin/activate"
echo "    code ."
